import Head from 'next/head'
import PostList from '../components/PostList'
//css kullanımı için bakabilirsin
import styles from '../styles/Home.module.css'

export default function Home({posts}) {
  console.log(posts)
  return (
    
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <PostList posts={posts}/>
    </div>
  )
}

//static generation kullanarak veriyi kullanacağımız alan
// bu sadece nextjs page comp için kullanabilir.
export const getStaticProps = async () => {
  const res = await fetch("https://jsonplaceholder.typicode.com/posts?_limit=5")
  const posts = await res.json()
  return {
    props: {
      posts,
    }
  }
}
